{{- $saEnabled := .Values.serviceAccount.create -}}
{{ with .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .commonAnnotations "context" $ ) | nindent 4 }}
spec:
  {{- if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{ include "common.labels.matchLabels" ( dict "customLabels" .podLabels "context" $ ) | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{ include "common.labels.standard" ( dict "customLabels" .podLabels "context" $ ) | nindent 8 }}
    spec:
      {{ if $saEnabled -}}
      serviceAccountName: {{ include "common.names.fullname" $ }}
      {{- end }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "common.names.name" $ }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          {{ $imageTpl := include "common.images.image" (dict "imageRoot" .image "global" $.Values.global) }}
          image: {{ include "common.tplvalues.render" (dict "value" $imageTpl "context" $) | quote }}
          {{ with .resources -}}
          resources:
          {{ include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
          {{- end }}
          {{ with .volumeMounts -}}
          volumeMounts: {{ include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12}}
          {{- end }}
          {{ with .ports -}}
          ports: {{ include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12}}
          {{- end }}
          {{ with .env -}}
          env:
          {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12}}
          {{- end }}
          {{ with .envFrom -}}
          envFrom:
          {{ include "common.tplvalues.render" (dict "value" . "context" $) | nindent 12}}
          {{- end }}
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{ end }}