{{- if and (.Values.ingress.enabled) (eq .Values.service.type "ClusterIP") }}
{{- with .Values.ingress -}}
{{- $host := .host -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .annotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
spec:
  {{ with .className -}}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ include "common.tplvalues.render" (dict "value" $host "context" $) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "common.names.fullname" $ }}
                port:
                  number: {{ include "common.tplvalues.render" (dict "value" $.Values.service.port "context" $) }}
  {{ with .tls }}
  tls:
    - hosts:
        - {{ include "common.tplvalues.render" (dict "value" $host "context" $) }}
  {{ end }}
{{- end -}}
{{- end }}