{{ with .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
spec:
  {{ with .type }}
  type: {{ include "common.tplvalues.render" (dict "value" . "context" $) }}
  {{ end }}
  ports:
    - port: {{ include "common.tplvalues.render" (dict "value" .port "context" $) }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "common.labels.matchLabels" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
{{ end }}