[package]
name = "wazuh-cert-oauth2-model"
version = "0.2.16"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1"
thiserror = "2"
jsonwebtoken = "9"
reqwest = { version = "0", features = ["json"] }
log = "0.4.22"