[package]
name = "wazuh-cert-oauth2-metrics"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
once_cell.workspace = true
opentelemetry.workspace = true
