name: Helm Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'charts/*/Chart.yaml'
      - '.github/workflows/helm-publish.yml'

jobs:
  deploy-helm:
    permissions:
      contents: write
      packages: write # Required for pushing to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: 'false'

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@bf6a7d304bc2fdb57e0331155b7ebf2c504acf0a # azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add repos to Helm
        run: |
          helm repo add bjw-s https://bjw-s-labs.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@419f3267f205afd4639d2eb12a64e911088a5d3d # helm/chart-releaser-action@v1
        if: github.ref == 'refs/heads/main'
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          skip_existing: false
          charts_dir: 'charts'
