name: Test install script

on: [ push, pull_request ]

jobs:
  test_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ steps.qemu.outputs.platforms }}

      - name: Test script
        run: |
          docker run --rm -v "$PWD:/app" bats/bats:latest /app/scripts/tests/test-script.bats
