[package]
name = "wazuh-cert-oauth2"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.1", features = ["full"] }
anyhow = "1.0.86"
thiserror = { version = "1.0.62" }
log = "0.4.22"
env_logger = "0.11.3"
rocket = { version = "0.5.1", features = ["tls", "json", "http2"] }
reqwest = { version = "0", features = ["json"] }
jsonwebtoken = "9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
openssl = "0.10.66"

[default.tls]
certs = "/usr/share/wazuh-cert-oauth2/certs/cert.pem"
key = "/usr/share/wazuh-cert-oauth2/certs/key.pem"
